const path = 'components/Authenticated/Modules/Registration';

export const GET_GENERICVALUESLIST = `${path}/GET_GENERICVALUESLIST`;
export const GET_GENERICVALUESLIST_SUCCESS = `${path}/GET_GENERICVALUESLIST_SUCCESS`;
export const GET_GENERICVALUESLIST_FAILURE = `${path}/GET_GENERICVALUESLIST_FAILURE`;

export const ADD_GENERICVALUES = `${path}/ADD_GENERICVALUES`;
export const ADD_GENERICVALUES_SUCCESS = `${path}/ADD_GENERICVALUES_SUCCESS`;
export const ADD_GENERICVALUES_FAILURE = `${path}/ADD_GENERICVALUES_FAILURE`;

export const GET_GENERICVALUES = `${path}/GET_GENERICVALUES`;
export const GET_GENERICVALUES_SUCCESS = `${path}/GET_GENERICVALUES_SUCCESS`;
export const GET_GENERICVALUES_FAILURE = `${path}/GET_GENERICVALUES_FAILURE`;

export const UPDATE_GENERICVALUES = `${path}/UPDATE_GENERICVALUES`;
export const UPDATE_GENERICVALUES_SUCCESS = `${path}/UPDATE_GENERICVALUES_SUCCESS`;
export const UPDATE_GENERICVALUES_FAILURE = `${path}/UPDATE_GENERICVALUES_FAILURE`;

export const DELETE_GENERICVALUES = `${path}/DELETE_GENERICVALUES`;
export const DELETE_GENERICVALUES_SUCCESS = `${path}/DELETE_GENERICVALUES_SUCCESS`;
export const DELETE_GENERICVALUES_FAILURE = `${path}/DELETE_GENERICVALUES_FAILURE`;

export const RESET_GENERICVALUES_FORM = `${path}/RESET_GENERICVALUES_FORM`;
